server:
  servlet:
    context-path: /helloWorld
  port: 8086
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: ybj
  redis:
    host: yuanbaojian.xyz
    port: 6379
    password: 312ybj
    database: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接，默认值也是0
        min-idle: 8
        # 连接池中的最大空闲连接，默认值也是0
        max-idle: 500
        # 连接池最大连接数
        max-active: 2000
        # 最长等待时间 ms
        max-wait: 10000
    timeout: 10000

  main:
    allow-bean-definition-overriding: true

#配置 elasticSearch的 url（已过失，过会再改）
  elasticsearch:
    jest:
      uris: http://127.0.0.1:9200


mybatis-plus:
  mapper-locations: classpath:com/ybj/crawler/mapping/*.xml
  type-aliases-package: com.ybj.crawler.model

