spring:
  datasource:
    username: rainBow
    password: 312ybj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yuanbaojian.xyz:3306/rain_bow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
